import { Session } from '../../types/session.types';
import { mockTrainers } from './mockTrainers';

export const mockSessions: Session[] = [
  {
    id: 's1',
    trainerId: 't1',
    traineeId: 'me',
    trainer: mockTrainers[0],
    type: 'virtual',
    status: 'upcoming',
    date: '2024-03-22',
    time: '07:00',
    duration: 60,
    price: 1800,
    meetLink: 'https://meet.google.com/abc-xyz',
    notes: 'Focus on deadlift form and progressive overload plan.',
  },
  {
    id: 's2',
    trainerId: 't2',
    traineeId: 'me',
    trainer: mockTrainers[1],
    type: 'virtual',
    status: 'upcoming',
    date: '2024-03-24',
    time: '08:30',
    duration: 45,
    price: 1200,
    meetLink: 'https://meet.google.com/def-uvw',
  },
  {
    id: 's3',
    trainerId: 't3',
    traineeId: 'me',
    trainer: mockTrainers[2],
    type: 'in-person',
    status: 'completed',
    date: '2024-03-15',
    time: '06:00',
    duration: 60,
    price: 2200,
    notes: 'Great HIIT session, 500 cals burned.',
  },
  {
    id: 's4',
    trainerId: 't7',
    traineeId: 'me',
    trainer: mockTrainers[6],
    type: 'virtual',
    status: 'completed',
    date: '2024-03-10',
    time: '19:00',
    duration: 30,
    price: 2000,
    notes: 'Nutrition plan updated for muscle building phase.',
  },
  {
    id: 's5',
    trainerId: 't1',
    traineeId: 'me',
    trainer: mockTrainers[0],
    type: 'virtual',
    status: 'live',
    date: '2024-03-20',
    time: '07:00',
    duration: 60,
    price: 1800,
    meetLink: 'https://meet.google.com/live-session',
  },
];
