import { Trainer } from '../../types/user.types';

export const mockTrainers: Trainer[] = [
  {
    id: 't1',
    userId: 'u1',
    name: 'Arjun Mehta',
    specialisation: ['Strength Training', 'Powerlifting'],
    rating: 4.9,
    reviewCount: 312,
    pricePerSession: 1800,
    photo: 'https://picsum.photos/seed/trainer1/400/400',
    verified: true,
    bio: 'Ex-national level powerlifter with 8 years of coaching experience. Helped 200+ clients transform their physique through progressive overload and smart nutrition.',
    tags: ['Beginner Friendly', 'Online', 'In-Person', 'Nutrition'],
    availability: ['Mon', 'Tue', 'Wed', 'Fri'],
    totalClients: 248,
    experience: 8,
    location: 'Mumbai, Maharashtra',
  },
  {
    id: 't2',
    userId: 'u2',
    name: 'Priya Sharma',
    specialisation: ['Yoga', 'Mobility'],
    rating: 4.8,
    reviewCount: 189,
    pricePerSession: 1200,
    photo: 'https://picsum.photos/seed/trainer2/400/400',
    verified: true,
    bio: 'Certified 500hr RYT yoga instructor specialising in Vinyasa and Yin yoga. Helping clients find balance, flexibility and inner peace.',
    tags: ['Beginner Friendly', 'Online', 'Flexibility', 'Mindfulness'],
    availability: ['Mon', 'Wed', 'Thu', 'Sat', 'Sun'],
    totalClients: 165,
    experience: 6,
    location: 'Bangalore, Karnataka',
  },
  {
    id: 't3',
    userId: 'u3',
    name: 'Rohan Kapoor',
    specialisation: ['HIIT', 'CrossFit'],
    rating: 4.7,
    reviewCount: 224,
    pricePerSession: 2200,
    photo: 'https://picsum.photos/seed/trainer3/400/400',
    verified: true,
    bio: 'CrossFit Level 2 trainer and HIIT specialist. Brutal workouts, incredible results. Not for the faint-hearted.',
    tags: ['Advanced', 'In-Person', 'Weight Loss', 'Endurance'],
    availability: ['Tue', 'Thu', 'Sat', 'Sun'],
    totalClients: 190,
    experience: 5,
    location: 'Delhi, NCR',
  },
  {
    id: 't4',
    userId: 'u4',
    name: 'Neha Joshi',
    specialisation: ['Pilates', 'Rehabilitation'],
    rating: 4.9,
    reviewCount: 156,
    pricePerSession: 2500,
    photo: 'https://picsum.photos/seed/trainer4/400/400',
    verified: true,
    bio: 'Certified Pilates instructor and physiotherapy assistant. Specialising in post-injury rehabilitation and core strengthening.',
    tags: ['Rehabilitation', 'Online', 'Core Strength', 'Posture'],
    availability: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri'],
    totalClients: 120,
    experience: 7,
    location: 'Pune, Maharashtra',
  },
  {
    id: 't5',
    userId: 'u5',
    name: 'Vikram Singh',
    specialisation: ['Boxing', 'MMA'],
    rating: 4.6,
    reviewCount: 98,
    pricePerSession: 3000,
    photo: 'https://picsum.photos/seed/trainer5/400/400',
    verified: false,
    bio: 'Former amateur boxing champion with 10+ years in combat sports. Teaching discipline, technique and serious conditioning.',
    tags: ['Combat Sports', 'In-Person', 'Cardio', 'Self-Defence'],
    availability: ['Mon', 'Wed', 'Fri', 'Sat'],
    totalClients: 85,
    experience: 10,
    location: 'Hyderabad, Telangana',
  },
  {
    id: 't6',
    userId: 'u6',
    name: 'Kavya Reddy',
    specialisation: ['Running', 'Endurance'],
    rating: 4.8,
    reviewCount: 143,
    pricePerSession: 1500,
    photo: 'https://picsum.photos/seed/trainer6/400/400',
    verified: true,
    bio: 'Marathon runner with 12 full marathons completed. Helping everyday runners go from couch to 5K to marathon finish lines.',
    tags: ['Running', 'Online', 'Marathon Prep', 'Beginner Friendly'],
    availability: ['Tue', 'Thu', 'Sat', 'Sun'],
    totalClients: 132,
    experience: 4,
    location: 'Chennai, Tamil Nadu',
  },
  {
    id: 't7',
    userId: 'u7',
    name: 'Amit Patel',
    specialisation: ['Nutrition', 'Weight Loss'],
    rating: 4.7,
    reviewCount: 267,
    pricePerSession: 2000,
    photo: 'https://picsum.photos/seed/trainer7/400/400',
    verified: true,
    bio: 'Certified sports nutritionist and fat loss specialist. No crash diets, no gimmicks — just science-backed sustainable nutrition.',
    tags: ['Nutrition', 'Online', 'Weight Loss', 'Meal Planning'],
    availability: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'],
    totalClients: 310,
    experience: 9,
    location: 'Ahmedabad, Gujarat',
  },
  {
    id: 't8',
    userId: 'u8',
    name: 'Sanya Kapoor',
    specialisation: ['Calisthenics', 'Mobility'],
    rating: 4.9,
    reviewCount: 88,
    pricePerSession: 1600,
    photo: 'https://picsum.photos/seed/trainer8/400/400',
    verified: true,
    bio: 'Calisthenics artist and movement coach. Teaching bodyweight mastery from beginner push-ups to handstands and muscle-ups.',
    tags: ['Calisthenics', 'Online', 'In-Person', 'Flexibility'],
    availability: ['Mon', 'Wed', 'Fri', 'Sun'],
    totalClients: 74,
    experience: 3,
    location: 'Kolkata, West Bengal',
  },
  {
    id: 't9',
    userId: 'u9',
    name: 'Dev Malhotra',
    specialisation: ['Strength Training', 'Bodybuilding'],
    rating: 4.5,
    reviewCount: 201,
    pricePerSession: 2800,
    photo: 'https://picsum.photos/seed/trainer9/400/400',
    verified: true,
    bio: 'Natural bodybuilder and strength coach. 10 years of competitive experience helping clients build muscle the right way.',
    tags: ['Bodybuilding', 'In-Person', 'Muscle Building', 'Advanced'],
    availability: ['Tue', 'Thu', 'Sat'],
    totalClients: 178,
    experience: 10,
    location: 'Jaipur, Rajasthan',
  },
  {
    id: 't10',
    userId: 'u10',
    name: 'Meera Iyer',
    specialisation: ['Cycling', 'Cardio'],
    rating: 4.8,
    reviewCount: 112,
    pricePerSession: 1400,
    photo: 'https://picsum.photos/seed/trainer10/400/400',
    verified: false,
    bio: 'Indoor cycling instructor and cardio enthusiast. High-energy classes that push your limits and torch calories.',
    tags: ['Cycling', 'Online', 'Cardio', 'Group Sessions'],
    availability: ['Mon', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'],
    totalClients: 203,
    experience: 5,
    location: 'Kochi, Kerala',
  },
];
